-- lib.be link shortener
-- database schema
-- 05/08/2013

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `libbe`
--
CREATE DATABASE IF NOT EXISTS `libbe` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `libbe`;
